config/routes.rb
Rails.application.routes.draw do
  root                 'static_pages#home'
  get       'about' => 'static_pages#about'
  resources :drafts
  resources :items
  resources :tags
  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }
  resources :users, param: :username, path: '/', only: [:show] do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/draft.rb
class Draft < ApplicationRecord
  belongs_to :user
  has_one :item
  acts_as_taggable
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :draft
  acts_as_taggable
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :drafts
  has_many :items
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                  foreign_key: "followed_id",
                                  dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  acts_as_taggable

  validates :username, uniqueness: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable, :omniauthable, omniauth_providers: [:twitter, :github]

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth["provider"], uid: auth["uid"]) do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.username = auth["info"]["nickname"]
    end
  end
  
  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"]) do |user|
        user.attributes = params
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def to_param
    username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception
  
  def hello
    render html: "hello, world!"
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password,
      :password_confirmation, :current_password, :image, :image_cache) }
  end

end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  before_action :set_draft, only: [:show, :edit, :update, :destroy]

  # GET /drafts
  # GET /drafts.json
  def index
    @drafts = current_user.drafts.all
    if params[:id].present?
      @draft = current_user.drafts.find(params[:id])
    end
  end

  # GET /drafts/1
  # GET /drafts/1.json
  def show
  end

  # GET /drafts/new
  def new
    @draft = current_user.drafts.build
  end

  # GET /drafts/1/edit
  def edit
  end

  # POST /drafts
  # POST /drafts.json
  def create
    @draft = current_user.drafts.build(draft_params)

    respond_to do |format|
      if @draft.save
        if params[:check_box_post]
          format.html { render :new } unless entry_item
        end
        format.html { redirect_to @draft, notice: 'Draft was successfully created.' }
        format.json { render :show, status: :created, location: @draft }
      else
        format.html { render :new }
        format.json { render json: @draft.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drafts/1
  # PATCH/PUT /drafts/1.json
  def update
    respond_to do |format|
      if @draft.update(draft_params)
        if params[:check_box_post]
          format.html { render :new } unless entry_item
        end
        format.html { redirect_to @draft, notice: 'Draft was successfully updated.' }
        format.json { render :show, status: :ok, location: @draft }
      else
        format.html { render :edit }
        format.json { render json: @draft.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drafts/1
  # DELETE /drafts/1.json
  def destroy
    @draft.destroy
    respond_to do |format|
      format.html { redirect_to drafts_url, notice: 'Draft was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_draft
      @draft = Draft.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def draft_params
      params.require(:draft).permit(:title, :content, :user_id, :tag_list)
    end

    def entry_item
      @item = current_user.items.find_by(draft_id: params[:id])
      @item = current_user.items.build if @item.nil?
      @item.title = draft_params[:title]
      @item.content = draft_params[:content]
      @item.user_id = @draft.user_id
      @item.draft_id = @draft.id
      @item.tag_list = @draft.tag_list
      @item.save
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def show
    @item = Item.find(params[:id])
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    @user = User.from_omniauth(request.env["omniauth.auth"].except("extra"))

    if @user.persisted?
      sign_in_and_redirect @user
    else
      session["devise.user_attributes"] = @user.attributes
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to user
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      following_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
      @items = Item.where("user_id IN (#{following_ids})
                           OR user_id = :user_id", user_id: current_user.id)
    end
  end

  def about
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by(username: params[:username])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # ページごとの完全なタイトルを返す
  def full_title(page_title = '')
    base_title = "Siita"
    if page_title.empty?
      base_title
    else
      page_title + " - " + base_title
    end
  end
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/drafts/_form.html.erb
<%= form_for(draft) do |f| %>
  <% if draft.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(draft.errors.count, "error") %> prohibited this draft from being saved:</h2>

      <ul>
      <% draft.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group form-group-lg">
    <%= f.label :title, class: "sr-only control-label" %>
    <%= f.text_field :title, placeholder: "タイトル", class: "form-control" %>
  </div>

  <div class="field form-group form-group-lg">
    <%= f.label :tag_list, class: "sr-only control-label" %>
    <%= text_field_tag 'draft[tag_list]', draft.tag_list.join(","), class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :content, class: "sr-only control-label" %>
    <%= f.text_area :content, placeholder: "本文",class: "form-control" %>
  </div>
  <div class="checkbox-inline">
    <%= check_box_tag :check_box_post, true, false, {} %>
    <%= label_tag :check_box_post, '<i class="fa fa-upload mr-5"></i>投稿する'.html_safe %>
  </div>
  <div>
    <%= button_tag '<i class="fa fa-floppy-o mr-5"></i>下書き保存'.html_safe, :type => "submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/drafts/edit.html.erb
<%= render 'form', draft: @draft %>

app/views/drafts/index.html.erb
<% provide(:title, "下書き一覧") %>
<div class="row">
  <div class="col-md-3 draftsSidebar">
    <div class="draftsSidebarHeader">
      <span>下書き一覧</span>
      <%= link_to (button_tag '<i class="fa fa-pencil"></i>'.html_safe, type: 'button', class: "btn btn-primary draftsSidebarHeader_btn"), new_draft_path %>
    </div>
    <ul class="nav nav-tabs">
      <li class="active"><a data-toggle="tab" href="#creatingDrafts">未投稿</a></li>
      <li><a data-toggle="tab" href="#editingDrafts">投稿済み</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="creatingDrafts">
        <table class="table table-hover">
          <tbody>
            <% @drafts.each do |draft| %>
              <tr data-link="<%= drafts_path(id: draft.id) %>">
                <td><%= draft.title %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="tab-pane" id="editingDrafts">
      </div>
    </div>
  </div>

  <div class="col-md-9 draftsPreview">
    <% unless @draft.nil? %>
    <div class="draftsPreviewMenu">
        <%= link_to (button_tag '<i class="fa fa-pencil"></i>編集'.html_safe, type: 'button', class: "btn btn-primary"), edit_draft_path(@draft) %>
        <%= link_to (button_tag '<i class="fa fa-trash"></i>削除'.html_safe, type: 'button', class: "btn btn-warning"), @draft, method: :delete, data: { confirm: 'Are you sure?'} %>
    </div>
    <div class="draftsPreviewContent_header">
      <h1 class="draftsPreviewContent_title">
        <%= @draft.title %>
      </h1>
      <p>
        <% @draft.tag_list.each do |tag| %>
          <span class="label label-primary"><%= tag %></span>
        <% end %>
      </p>
    </div>
    <div class="draftsPreviewContent_body">
      <p>
        <%= @draft.content %>
      </p>
    </div>
    <% end %>
  </div>
</div>

app/views/drafts/new.html.erb
<% provide(:title, "新規投稿") %>
<%= render 'form', draft: @draft %>

app/views/drafts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @draft.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @draft.content %>
</p>

<% @draft.tag_list.each do |tag| %>
    <span class="label label-primary"><%= tag %></span>
<% end %>

<p>
  <strong>User:</strong>
  <%= @draft.user %>
</p>

<%= link_to '編集', edit_draft_path(@draft) %> |
<%= link_to '戻る', drafts_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @item.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @item.user %>
</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <small>&copy; 2017 ShunjiKato</small>
    <nav>
      <ul>
        <li><%= link_to "Siitaとは", about_path %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <div class="container">
    <div class="header-left">
      <%= link_to "Siita", root_path, id: "logo" %>
    </div>
    <div class="header-right">

      <% if user_signed_in? %>
        <div class="btn-group" role="group">
          <%= button_tag onclick: "Turbolinks.visit('#{new_draft_path}')",
              type: :button, class: "btn btn-primary" do %>
              <%= '<i class="fa fa-pencil mr-5"></i>投稿する'.html_safe %>
          <% end %>
          <button class="btn btn-primary dropdown-toggle pull-right" type="button" id="dropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu">
            <li><%= link_to '<i class="fa fa-files-o"></i>下書き'.html_safe, drafts_path %></li>
          </ul>
        </div>
        <%= link_to "ストック一覧", '#', class: "btn-link" %>
        <div class="btn-group" role="group">
          <% if current_user.image.url.nil? %>
            <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-user-circle"></i>
            </button>
          <% else %>
            <%= image_tag(current_user.image.url(:thumb), size: "32x32", class: "img-rounded dropdown-toggle clickable",
                          data: {toggle: "dropdown" }) %>
          <% end %>
          <ul class="dropdown-menu pull-right">
            <li><%= link_to '<i class="fa fa-gear"></i>設定'.html_safe, edit_user_registration_path, method: :get %></li>
            <li><%= link_to '<i class="fa fa-sign-out"></i>ログアウト'.html_safe, destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      <% else %>
        <%= link_to (button_tag "ユーザ登録", type: 'button', class: "btn btn-warning"), new_user_registration_path %>
        <%= link_to "ログイン", new_user_session_path, class: "btn-link" %>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if It IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% if notice.present? %>
        <div class="alert alert-success" role="alert">
          <button class="close" data-dismiss="alert">&times;</button>
          <%= notice %>
        </div>
      <% end %>
      <% if alert.present? %>
        <div class="alert alert-danger" role="alert">
          <button class="close" data-dismiss="alert">&times;</button>
          <%= alert %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "Siitaとは") %>
<h1>StaticPages#about</h1>
<p>simple idea in technology architect</p>

app/views/static_pages/home.html.erb
<% provide(:title, "ホーム") %>
<% if user_signed_in? %>
    <div class="row">
      <div class="col-md-9">
        <div class="feedPage_header">
          <h2>プログラミング知識を共有しよう</h2>
          <%= link_to (button_tag "ノウハウ・Tipsを投稿する", type: 'button', class: "btn btn-primary"), new_draft_path %>
        </div>
        <div class="streamContainer">
          <nav>
            <ul class="nav nav-tabs">
              <li class="active"><a data-toggle="tab" href="#">フィード</a></li>
              <li><a data-toggle="tab" href="#">すべての投稿</a></li>
            </ul>
          </nav>
          <div class="tab-content">
            <div class="tab-pane active" id="creatingDrafts">
              <table class="table table-hover">
                <tbody>
                <% @items.each do |item| %>
                    <tr data-link="<%= item_path(id: item.id) %>">
                      <td><%= item.title %></td>
                    </tr>
                <% end %>
                </tbody>
              </table>
            </div>
            <div class="tab-pane" id="">
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div>
        </div>
      </div>
    </div>
<% else %>
<% end %>

app/views/tags/index.html.erb
<% provide(:title, "タグ一覧") %>
<div class="row">
  <% @tags.each_with_index do |tag, index| %>
    <% if index % 5 == 0 %>
      <div class="row">
    <% end %>
      <div class="col-md-3">
      <tr>
        <td><%= tag.name %></td>
      </tr>
    <% if index % 5 == 0 %>
      </div>
  <% end %>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user.equal?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: {method: :delete},
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class="row userPage">
  <div class="col-md-3">
    <% if @user.image.url.present? %>
      <%= image_tag(@user.image.url, size: "165x165", class: "img-rounded")  %>
    <% else %>
      <div class="userNoImage">No Image</div>
    <% end %>
    <h3><%= @user.username %></h3>
    <%= render 'follow_form' if user_signed_in? && @user.id != current_user.id %>
    <div>
      <i class="fa fa-users"></i>フォロー中のユーザー
        <strong id="following" class="stat">
          <%= @user.following.count %>
        </strong>
    </div>
  </div>
  <div class="col-md-9"></div>
</div>